# Generated by Django 4.0.4 on 2022-05-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(help_text='Макс 70 символов', max_length=70, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(help_text='Макс 70 символов', max_length=70, verbose_name='Название'),
        ),
    ]
