# Generated by Django 4.0.4 on 2022-05-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_conference_title_alter_lecture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(
                help_text='Макс 70 символов',
                max_length=70,
                unique=True,
                verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(
                help_text='Макс 150 символов',
                max_length=150,
                verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(
                help_text='Макс 150 символов',
                max_length=150,
                verbose_name='Название'),
        ),
    ]
