# Generated by Django 4.0.4 on 2022-05-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='conference',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='conference',
            name='slug',
            field=models.SlugField(default=None, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(default=None, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
