# Generated by Django 4.0.4 on 2022-05-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_category_is_active_conference_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(help_text='Макс 150 символов', max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(help_text='Макс 150 символов', max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
