# Generated by Django 4.0.4 on 2022-05-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_conference_title_alter_lecture_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='confirmed',
            field=models.BooleanField(
                default=False,
                verbose_name='Утверждена'),
        ),
    ]
