# Generated by Django 4.0.4 on 2022-05-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_lecture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(upload_to='uploads', verbose_name='Презентация'),
        ),
    ]
