# Generated by Django 4.0.4 on 2022-05-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_lecture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
