# Generated by Django 4.0.4 on 2022-05-24 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_conference_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(
                upload_to='uploads',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['pdf'])],
                verbose_name='Презентация'),
        ),
    ]
