# Generated by Django 4.0.4 on 2022-05-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_lecture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='desired_time',
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name='Желаемое время'),
        ),
    ]
