# Generated by Django 4.0.4 on 2022-05-24 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Презентация'),
        ),
    ]
