# Generated by Django 4.0.4 on 2022-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_conference_upload_alter_lecture_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
